/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tr.NW09.antihilepublic;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.PrintWriter;
import java.io.StringWriter;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Userxxx
 */
public class Gui extends javax.swing.JFrame {
    public static String Version = "0.4";
    private static String SonHata = "";
    public static JLabel Durum;
    public static String Domain = "http://127.0.0.1";

    /**
     * Creates new form AntiHilePublic
     */
    public Gui() {
        initComponents();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/tr/NW09/antihilepublic/icon/AnadoluNW.png")).getImage());
        version.setText("Version V " + Version);
        tekrardene.setVisible(false);
        adim1.setVisible(false);
        adim2.setVisible(false);
        adim3.setVisible(false);
        adim4.setVisible(false);
        adim5.setVisible(false);
        Gui.Durum = this.DurumMesaji;
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        try {

        } catch (Exception ex) {
            StringWriter errors = new StringWriter();
            ex.printStackTrace(new PrintWriter(errors));
            LogAl(LogTur.HATA, errors.toString());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adim1 = new javax.swing.JLabel();
        adim2 = new javax.swing.JLabel();
        adim3 = new javax.swing.JLabel();
        adim4 = new javax.swing.JLabel();
        adim5 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        DurumMesaji = new javax.swing.JLabel();
        tekrardene = new javax.swing.JButton();
        version = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Anti-Hile Client");
        setBackground(new java.awt.Color(255, 255, 255));

        adim1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        adim1.setText("Proccesler Inceleniyor...");
        adim1.setToolTipText("");

        adim2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        adim2.setText("Veriler Ayıklanıyor...");
        adim2.setToolTipText("");

        adim3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        adim3.setText("Baglantilar Kontrol Ediliyor...");
        adim3.setToolTipText("");

        adim4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        adim4.setText("Client Inceleniyor...");
        adim4.setToolTipText("");

        adim5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        adim5.setText("Sunucu ile Baglantiya Geciliyor...");
        adim5.setToolTipText("");

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/NW09/antihilepublic/icon/logo.png"))); // NOI18N

        DurumMesaji.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DurumMesaji.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DurumMesaji.setText("Durum Mesajı");

        tekrardene.setText("Tekrar Dene");
        tekrardene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tekrardeneActionPerformed(evt);
            }
        });

        version.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        version.setText("Version V");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(icon)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(adim1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adim2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adim3, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adim5, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adim4, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(tekrardene)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(DurumMesaji, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(version, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(adim1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adim2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adim3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adim4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adim5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tekrardene))
                    .addComponent(icon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DurumMesaji, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(version))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tekrardeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tekrardeneActionPerformed
        tekrardene.setVisible(false);
        adim1.setVisible(false);
        adim2.setVisible(false);
        adim3.setVisible(false);
        adim4.setVisible(false);
        adim5.setVisible(false);
        Gui.Durum = this.DurumMesaji;
        new Thread(new ArkaPlanislemci((this))).start();
    }//GEN-LAST:event_tekrardeneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Gui gui = new Gui();
                gui.setVisible(true);
                new Thread(new ArkaPlanislemci(gui)).start();
            }
        });
    }

    public static void LogAl(LogTur Tur, String Message) {
        if (Tur == LogTur.HATA) {
            SonHata = Message;
            Gui.Durum.setText("Hata: " + Message);
            Gui.Durum.setForeground(Color.RED);
        } else if (Tur == LogTur.BILGI) {
            Gui.Durum.setText(Message);
            Gui.Durum.setForeground(Color.BLUE);
        }
        System.out.println(Tur.OnEk() + " " + Message);
    }

    public void AdimBasla(Adimlar adim) {
        switch (adim) {
            case VersionKontrol:
                Durum.setForeground(Color.blue);
                Durum.setText(adim.getOnce());
                break;
            case Adim1:
                adim1.setVisible(true);
                adim1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/NW09/antihilepublic/icon/loading.gif")));
                adim1.setText(adim.getOnce());
                break;
            case Adim2:
                adim2.setVisible(true);
                adim2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/NW09/antihilepublic/icon/loading.gif")));
                adim2.setText(adim.getOnce());
                break;
            case Adim3:
                adim3.setVisible(true);
                adim3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/NW09/antihilepublic/icon/loading.gif")));
                adim3.setText(adim.getOnce());
                break;
            case Adim4:
                adim4.setVisible(true);
                adim4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/NW09/antihilepublic/icon/loading.gif")));
                adim4.setText(adim.getOnce());
                break;
            case Adim5:
                adim5.setVisible(true);
                adim5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/NW09/antihilepublic/icon/loading.gif")));
                adim5.setText(adim.getOnce());
                break;
        }
    }

    public void AdimGec(Adimlar adim) {
        switch (adim) {
            case VersionKontrol:
                Durum.setForeground(Color.blue);
                Durum.setText(adim.getSonra());
                break;
            case Adim1:
                adim1.setText(adim.getSonra());
                adim1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/NW09/antihilepublic/icon/tik.png")));
                break;
            case Adim2:
                adim2.setText(adim.getSonra());
                adim2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/NW09/antihilepublic/icon/tik.png")));
                break;
            case Adim3:
                adim3.setText(adim.getSonra());
                adim3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/NW09/antihilepublic/icon/tik.png")));
                break;
            case Adim4:
                adim4.setText(adim.getSonra());
                adim4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/NW09/antihilepublic/icon/tik.png")));
                break;
            case Adim5:
                adim5.setText(adim.getSonra());
                adim5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/NW09/antihilepublic/icon/tik.png")));
                //son adim
                Gui.Durum.setText("Bilgilerin Basariyla Iletildi.Program 3 Saniye icinde Kapanacak.");
                Gui.Durum.setForeground(Color.GREEN);
                try {
                    Thread.sleep(3000);
                } catch (Exception e) {

                }
                System.exit(0);
                break;
        }
    }

    public void AdımHata(Adimlar adim) {
        if(adim != Adimlar.VersionKontrol){
        tekrardene.setVisible(true);
        }
        switch (adim) {
            case VersionKontrol:
                JOptionPane.showMessageDialog(this, adim.getHint(SonHata), "Hata:" + adim.getOnce(), JOptionPane.ERROR_MESSAGE, null);
                break;
            case Adim1:
                adim1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/NW09/antihilepublic/icon/carpi.png")));
                JOptionPane.showMessageDialog(this, adim.getHint(SonHata), "Hata:" + adim.getOnce(), JOptionPane.ERROR_MESSAGE, null);
                break;
            case Adim2:
                adim2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/NW09/antihilepublic/icon/carpi.png")));
                JOptionPane.showMessageDialog(this, adim.getHint(SonHata), "Hata:" + adim.getOnce(), JOptionPane.ERROR_MESSAGE, null);
                break;
            case Adim3:
                adim3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/NW09/antihilepublic/icon/carpi.png")));
                JOptionPane.showMessageDialog(this, adim.getHint(SonHata), "Hata:" + adim.getOnce(), JOptionPane.ERROR_MESSAGE, null);
                break;
            case Adim4:
                adim4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/NW09/antihilepublic/icon/carpi.png")));
                JOptionPane.showMessageDialog(this, adim.getHint(SonHata), "Hata:" + adim.getOnce(), JOptionPane.ERROR_MESSAGE, null);
                break;
            case Adim5:
                adim5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/NW09/antihilepublic/icon/carpi.png")));
                JOptionPane.showMessageDialog(this, adim.getHint(SonHata), "Hata:" + adim.getOnce(), JOptionPane.ERROR_MESSAGE, null);
                break;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DurumMesaji;
    private javax.swing.JLabel adim1;
    private javax.swing.JLabel adim2;
    private javax.swing.JLabel adim3;
    private javax.swing.JLabel adim4;
    private javax.swing.JLabel adim5;
    private javax.swing.JLabel icon;
    private javax.swing.JButton tekrardene;
    private javax.swing.JLabel version;
    // End of variables declaration//GEN-END:variables
}
